### ISSUE TITLE
The shader material is pink in the editor view.

### ISSUE THREAD

**Issue by ryu-esque** [asus4/unity-neumorphism-ui#2]
When using this project in Universal Render Pipeline,  the neumorphism material is shown as pink, in the editor. When I hit play, it works fine. It works fine both in editor and play mode when I'm using scriptable render pipeline. This issue seems to be present only in the editor mode of the Universal Render Pipeline.

When I try upgrading the material to URP via unity's built in URP material upgrade tool, I get this error "Neumorphism material was not upgraded. There's no upgrader to convert UI/Neumorphism shader to selected pipeline".

The upgrade has to be done manually and I'm not familiar enough with shaders to do so. Any help would be appreciated. Thanks.

**Comment by asus4** [comment]
It's too slow to update here 😅  but I fixed that error at #3
